use_frameworks!

platform :ios, '9.0'

target 'MediastreamPlatformSDKxC_Example' do
  pod 'MediastreamPlatformSDKxC', :path => '../'

  target 'MediastreamPlatformSDKxC_Tests' do
    inherit! :search_paths

    
  end
end
